apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-app-1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/d2krish/gitops-training-with-vilas
